name: my first workflow in action

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: step1 
        run: echo "welcome to job1"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: step2
        run : | 
              echo "my step2 execution"
              hostname
              date
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: show predefined variables
        run: | 
             echo "my repo: $GITHUB_REPOSITORY"
             echo "branch: $GITHUB_REF"
             echo "triggered by: $GITHUB_ACTOR"
             echo "my city:  $city"
 
